### PR TITLE
Add automatic tests

### PR DESCRIPTION
**Pull request by jankatins**

### CODE REVIEW

**Comment by jankatins** [comment]
Some more test would be nice... :-)

**Comment by jankatins** [comment]
The packages currently passes all my local `R CMD check` (3.3, 3.3, devel)

**Comment by jankatins** [comment]
Ok, it seems that I don't have enough rights here to enable the travis builds. Could someone of you enable them? @takluyver @flying-sheep

**Comment by takluyver** [comment]
Hurray, tests! I have flipped the switch on Travis, I think you'll need to push another commit for it to get notified and run tests.

**Comment by jankatins** [comment]
repushed

**Comment by flying-sheep** [comment]
> Dependency package roxygen2 not available

**Comment by jankatins** [comment]
updated and repushed...

**Comment by takluyver** [comment]
Tada!

**Pull request merged**
