### PR TITLE
Fixed a typo which leads to a plotting error.

### PR DESCRIPTION
**Pull request by chenye**
While I was trying to plot a figure in Jupyter using R kernel, an error popped out said that:
"Error in display_png(filename = tf): unused argument (filename = tf)"

### CODE REVIEW

**Comment by takluyver** [comment]
I think I've just fixed this in IRkernel, by making the opposite change. I
don't know if anyone else is using this API directly - if they are,
changing it back to filename may be preferable.

**Comment by chenye** [comment]
I just installed Jupyter yesterday and installed IRkernel and IRdisplay this afternoon. Then I tried to use it to plot some figures in notebook but no figure displayed and it returned an error message. Maybe the IRkernel is updated this afternoon (US pacific time)? I'll check if problem still exists after re-install IRkernel tomorrow (Right now I am using it to do some analysis :) ).

**Comment by flying-sheep** [comment]
whoops, sorry my bad. i didn’t propagate the chage to IRkernel!

`file` is better than `filename`, since `base64encode()` also accepts file handles returned by `file()`

and we’re an experimental project anyway, so changes like this can happen… i’m still very sorry i didn’t change both!

**Comment by takluyver** [comment]
IRkernel was indeed updated yesterday afternoon pacific time: https://github.com/IRkernel/IRkernel/commit/0916f0a604212b9929487ecb63991a7158226735

**Comment by flying-sheep** [comment]
yep, already saw and edited my comment, sorry for the confusion.

**Comment by chenye** [comment]
Now I see why I was not able to plot figures yesterday. It seems like I just installed the package at a really "lucky" time right in the middle of two related updates. But thanks for the clarification. It's good that it works.

**Pull request closed without merging**
