### PR TITLE
Use stdout for the default base_display

### PR DESCRIPTION
**Pull request by flying-sheep**
Why not do sth useful by default?

### CODE REVIEW

**Comment by jankatins** [comment]
So that one can use `display_something(...)` in other packages without thinking about the backend?

Is there actually a way to make the display package useful in RStudio or knitr? In RStudio one could send html to the viewer, display plain text and payloads / Pages could be displayed as a new page (not sure if we actually have a display function for that. I guess not?). In knitr I don't know. The display machinery there is based on return values but `display_xxx` doesn't do that...

**Comment by takluyver** [comment]
Flip side: if you just want to display plain text, you have `print()`. If you want to explicitly display rich output, an error explaining why it won't work might be better than a plain text display. I'm not sure there are many cases where a rich display is useful but a text fallback is fine.

This is partly a strawman comment - I can vaguely imagine possible uses. But the equivalent machinery in `IPython.display` does not work outside of IPython, and I don't remember anyone ever wishing that it fell back to print().

**Comment by flying-sheep** [comment]
hmm, yeah. either we stay with “IRdisplay is the user interface for IRkernel’s display machinery” or make it “`display` is something you put into your personal utility functions instead of `print`”

**Comment by takluyver** [comment]
I suspect that as @janschulz said, the key is whether it is feasible (and makes sense from a UX perspective) to do rich display from this API in RStudio and knitr. My instinct is that there will be enough difference in the way those things work that this API is not easily compatible, and it might make more sense to have a separate higher level API which picks the appropriate low level display API to use. But I haven't investigated RStudio or knitr at all.

**Comment by jankatins** [comment]
My "design goal" was always to make `repr` the reusable part and `IRdisplay` more or less only useable in `IRKernel` (which is only in a different package because the audiences are different: on is usable in interactive work, on is not...).

In IPython there are three ways to "submit" stuff to the display system: implement the magic methods in an object (e.g. `DataFrame._repr_html_()`) or implementing a display function for a data type and activate it in the display machinery (both kind of like `repr_xxx.data.type()` and the stuff in  `repr`) and the `display_xxx` functions itself. I've actually not seen so many stuff done with the display functions, most stuff I've seen (in packages) implements either the magic functions or activates a display function for a data type. The only advantage over using display vs return a data structure is that you can call display multiple time vs you have to collect all output to get it displayed via the returned object. which is IMO a really small use case outside the notebook where you mostly either can only display one thing at a time (RStudio viewer) or have linear output which is similar to printing stuff :-/ 

So IMO we should encourage the use of `repr` and therefore don't need to make the `display` package useable outside of the kernel... If someone wants to make use of the repr work, they need to implement the "display loop" anyways (like `IRkernel` currently does) and if they want to use `IRdisplay`, they will also implement a base display function. 

On the other hand: the only think what could hurt be this PR is that some users use IRdisplay in packages code because it kind of works and then users don't like it when they use the package outside of IRkernel.

**Comment by flying-sheep** [comment]
OK, good points. i’m closing this.

**Pull request closed without merging**
