### PR TITLE
Add a clear_output function to IRdisplay

### LINKED ISSUE #432: clear_output from code
This is repeat of a question I posted on stack-overflow (no response there so hopefully someone here can help):

I am trying to incrementally plot a graph, animating the progress of an image registration process. In a Python notebook this is done by repeatedly plotting and clearing the output. A MWE:

```py
import matplotlib.pyplot as plt
%matplotlib inline
import time

from IPython.display import clear_output

values = (1.23, 4.5, 1.23, 4.5)
for i in range(1,5):
    clear_output(wait=True)
    plt.plot(0, values[0], 'b*')
    plt.plot(values[0:i], 'r')
    time.sleep(0.5)
    plt.show()
```

The equivalent in R (missing the clear-output):

```r
values <- c(1.23, 4.5, 1.23, 4.5)

for (i in 1:4) {
  # clear output
  plot(values[1:i], type="l", las=1, col="red")
  points(1, values[1], col="blue", pch=18)
  Sys.sleep(0.5)
}
```

In practice the plots will not be created in a for-loop, these are callbacks from the computationally intensive image registration. I am using the for loop as the MWE.

Is it possible to programmatically clear the output using the ir kernel? If yes, how? If not, any suggestions on creating animations in the notebook. This needs to be an online solution - saving images and creating an animated gif is not relevant for this purpose.

For those curious about the specific goal, this is part of our development of Jupyter [SimpleITK notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).

Any advice is much appreciated.

### PR DESCRIPTION
**Pull request by michaelquinn32**
Fixes IRkernel/IRkernel#432

### CODE REVIEW

**Comment by michaelquinn32** [comment]
Hi @flying-sheep!

This is the other half of IRkernel/IRkernel#432. Mind taking a look?

Thanks!

**Comment by flying-sheep** [comment]
On it!

**Comment by flying-sheep** [comment]
Could you please fix the warning?

> Undocumented arguments in documentation object 'publish_mimebundle'
>
> Functions with \usage entries need to have the appropriate \alias entries, and all their arguments documented.

**Comment by michaelquinn32** [comment]
Thanks for catching that!

**Comment by matthewgasbarro** [comment]
Hello when will this be released? Same for https://github.com/IRkernel/IRkernel/issues/432  Thanks!.

**Comment by flying-sheep** [comment]
I’ll take care of it. Since Travis is going the way of the dodo, I’ll have to convert IRkernel’s CLI to GH actions or so, then release IRkernel, then merge & release this

**Comment by flying-sheep** [comment]
OK, IRkernel builds are green, now I just need to convert this one and wait for CRAN to come out of vacation

**Comment by flying-sheep** [comment]
OK, submitted! IRkernel 1.3 and IRdisplay 1.1 together should do the trick.

**Comment by matthewgasbarro** [comment]
Thanks so much. Works as expected!

**Pull request merged**
