### PR TITLE
Create a reusable prepare_mimebundle function with custom error handling

### PR DESCRIPTION
**Pull request by flying-sheep**
This aims to
1. separate the “create mimebundle” step from “display stuff from mimebundle” (`display` is now only a small wrapper that does both)
2. add configurability like an error handler and the mime types to use
3. be usable in the kernel (IRkernel/IRkernel#368)

I’m not final on the design, though: the set of IRdisplay functions doesn’t seem too consistent or generally useful. we’ll have to think about which ones we really need before publishing it on CRAN

also we need to think about `prepare_content` (which converts raw vectors to base64): we don’t need it since our JSON serializer does that already: do we change the signature of `prepare_mimebundle` and `display_raw` so that they emit raw vectors?

### CODE REVIEW

**Comment by takluyver** [comment]
The minimum public API that I think IRdisplay needs would include:
- Given a mimebundle dict (i.e. named list in R) of pre-prepared data, send it as a display_data message - this is `publish_mimebundle` currently.
- Given an object, produce all appropriate (whatever that means...) formats and send the display_data message (`display()`).
- Some means to send only a specific format - either as separate functions like `display_html`, or via a parameter, e.g. `display_formats(..., 'text/html')`. Not sure if this should include the formatting step, or not, or if we should provide both.

That's not to say other functions shouldn't be there, but off the top of my head that's the minimum set to build on.

**Comment by flying-sheep** [comment]
good point: so we want to have as output always something displaying (i.e. a bundle published), and as input several formats: an object to be repr’d, data of a certain kind, and the low-level mimebundle

the kernel needs the first half of the “object to be repr’d” function (`display`), but does the publishing itself.

does the resulting function (which i called `prepare_mimebundle`) have a place in IRdisplay? if not, where to put it? it’s to be used by IRdisplay and IRkernel…

**Comment by flying-sheep** [comment]
@takluyver what do you mean?

the tests pass my only change is adding a function… do you think its signature and name are fitting?

**Comment by takluyver** [comment]
I'm happy for prepare_mimebundle to be in IRdisplay or in repr - if we're trying to make repr a more generic system that consumers other than Jupyter can accept, then maybe `prepare_mimebundle` doesn't belong there. On the other hand, while mimebundles come from Jupyter, it's a useful concept that other code may want to use.

**Comment by flying-sheep** [comment]
the metadata format however is jupyter specific.

**Comment by takluyver** [comment]
The message metadata is - the content metadata in a mimebundle could be
used by other things, potentially.

**Comment by flying-sheep** [comment]
still, by now repr is pretty pure in what it does and i’d like to keep it that way.

IRdisplay has “Jupyter R kernel” written all over it, and already interacts with the mimebundle interface (`list(data = …, metadata = …)`) so even if that new function doesn’t straight up display something, I think it fits there best.

**Comment by takluyver** [comment]
Fine by me :)

**Comment by flying-sheep** [comment]
also: should we remove the base64 encoding? as said: our JSON impl does it already, we can get rid of a dependency, and i’m sure nobody other that IRkernel relies on mimebundle publishing yet.

**Comment by flying-sheep** [comment]
OK, then I’d say we do :wink:

**Pull request merged**
