### PR TITLE
Add a better way to set the base_display function

### PR DESCRIPTION
**Pull request by jankatins**
Adresses the problem in https://github.com/IRkernel/IRkernel/issues/257#issuecomment-217618492

### CODE REVIEW

**Comment by flying-sheep** [comment]
good idea, but why `_func`? is there another `jupyter.base_dispay` option?

**Comment by takluyver** [comment]
I think it's reasonable enough to add _func to the name to make it more obvious what it is. `base_display` would not be so clear.

**Comment by takluyver** [comment]
(The Travis failure is just because master didn't have .travis.yml when it tested this PR, so it tried to run it with the default settings for a ruby project)

**Comment by jankatins** [comment]
closed/reopen to rerun travis

**Comment by takluyver** [comment]
Oh, neat trick, I didn't know that that worked.

**Comment by flying-sheep** [comment]
great stuff

**Pull request merged**
