### PR TITLE
Add tests for the display functions

### PR DESCRIPTION
**Pull request by jankatins**
Closes: https://github.com/IRkernel/IRdisplay/issues/24

### CODE REVIEW

**Comment by jankatins** [comment]
Ok, this doesn#t work (the rest does...). No idea how that works with raw ones...

``` R
test_that("display_png works", {
    exp <- namedlist()
    exp_metadata = namedlist()
    display_png(as.raw("data"))
    exp[['image/png']] <- base64encode(as.raw("data"))
    print("--")
    f <- get_last_data()
    print(f)
    print("--")
    print(exp)
    print("--")
    expect_equal(f,list(exp, NULL))
    display_png(as.raw("data"), width = 1, height = 2)
    exp_metadata$width  <- 1
    exp_metadata$height <- 2
    expect_equal(get_last_data(),list(exp, exp_metadata))
})
```

```
display functions: ......1.2.WWWW[1] "--"
[[1]]
[[1]]$`image/png`
[1] "AA=="


[[2]]
named list()

[1] "--"
$`image/png`
[1] "AA=="

[1] "--"
3WW.

Warnings -----------------------------------------------------------------------
1. display_png works (@test_display_functions.R#85) - NAs introduced by coercion

2. display_png works (@test_display_functions.R#85) - out-of-range values treated as 0 in coercion to raw

3. display_png works (@test_display_functions.R#86) - NAs introduced by coercion

4. display_png works (@test_display_functions.R#86) - out-of-range values treated as 0 in coercion to raw

5. display_png works (@test_display_functions.R#94) - NAs introduced by coercion

6. display_png works (@test_display_functions.R#94) - out-of-range values treated as 0 in coercion to raw

Failed -------------------------------------------------------------------------
1. Failure: display_javascript works (@test_display_functions.R#58) ------------
get_last_data() not equal to list(exp, NULL).
Component 1: Names: 1 string mismatch
```

**Comment by flying-sheep** [comment]
Cool!

style stuff:

``` bash
for file in tests/testthat/*.R; do
    sed -i "s/\"/'/g" "$file"
    mv "$file" "$(basename "$file" .R).r"
done
```

**Comment by jankatins** [comment]
Sorry, windows giut has no difference between `.R` and `.r`, so someone on *ix needs to rename the `test_options.R`. The rets I got via a `git reset HEAD~`, but I don't wanna rewrite history in the master branch.

**Comment by jankatins** [comment]
Added tests for all functions, but not for the file code paths...

**Comment by jankatins** [comment]
IMO mergeable and then releaseable and submitteable

**Comment by flying-sheep** [comment]
well, it was almost ready @69fd5d82b0890f07d00767b2927697896247bc1b :wink:

**Comment by jankatins** [comment]
Damn, sorry, I did that, but it seems that I did it in the already opened files in RStudio and not the new ones with lower case 'r' :-(

**Comment by flying-sheep** [comment]
NP! you did the important work.

**Pull request merged**
